### ISSUE TITLE
Доработки по РК 2

### ISSUE THREAD

**Issue by vileven** [frontend-park-mail-ru/2018_1_unnamed_project#15]
- [x] Пофиксить баг с resize окна при игре
- [x] Сделать ошибки на одном языке, и в принципе подумать как их показывать, сейчас оно не очень консистентно с общий дизайном выглядит.
- [x] Неочевидно, что ссылка на регистрацию действительно ссылка, а не текст. Надо бы её как то выделить. Тоже подумайте
- [x] Добавьте красивое описание как играть, а лучше туториал!

А вообще вы большие молодцы!

**Comment by gabolaev** [comment]
Исправлено: https://github.com/frontend-park-mail-ru/2018_1_unnamed_project/pull/16
Туториал позже завезём)

**Comment by gabolaev** [comment]
Описание правил будет тут: https://github.com/frontend-park-mail-ru/2018_1_unnamed_project/pull/19
